d_solicitud = {
    "0": "Token invalido",
    "1": "Aceptada",
    "2": "En proceso",
    "3": "Terminada",
    "4": "Error",
    "5": "Rechazada",
    "6": "Vencida"
    }
d_estatus = {
    "300": "Usuario No Válido",
    "301": "XML Mal Formado Este código de error se regresa cuando el request posee información invalida, ejemplo: un RFC de receptor no válido",
    "302": "Sello Mal Formado",
    "303": "Sello no corresponde con RfcSolicitante",
    "304": "Certificado Revocado o Caduco El certificado fue revocado o bien la fecha de vigencia expiró",
    "305": "Certificado Inválido El certificado puede ser invalido por múltiples razones como son el tipo, codificación incorrecta, etc"
    }
d_estado = {
    "5000": "Solicitud recibida con éxito",
    "5002": "Se agotó las solicitudes de por vida",
    "5003": "Tope máximo (Más de ~200,000 CFDI)",
    "5004": "No se encontró la información",
    "5005": "Solicitud duplicada",
    "404": "Error no controlado"
    }

c_TipoRelacion = {
    "01": "01 Nota de crédito de los documentos relacionados",
    "02": "02 Nota de débito de los documentos relacionados",
    "03": "03 Devolución de mercancía sobre facturas o traslados previos",
    "04": "04 Sustitución de los CFDI previos",
    "05": "05 Traslados de mercancías facturados previamente",
    "06": "06 Factura generada por los traslados previos",
    "07": "07 CFDI por aplicación de anticipo"
    }
c_UsoCFDI = {
    "G01": "G01 Adquisición de mercancías",
    "G02": "G02 Devoluciones, descuentos o bonificaciones",
    "G03": "G03 Gastos en general",
    "I01": "I01 Construcciones",
    "I02": "I02 Mobiliario y equipo de oficina por inversiones",
    "I03": "I03 Equipo de transporte",
    "I04": "I04 Equipo de computo y accesorios",
    "I05": "I05 Dados, troqueles, moldes, matrices y herramental",
    "I06": "I06 Comunicaciones telefónicas",
    "I07": "I07 Comunicaciones satelitales",
    "I08": "I08 Otra maquinaria y equipo",
    "D01": "D01 Honorarios médicos, dentales y gastos hospitalarios",
    "D02": "D02 Gastos médicos por incapacidad o discapacidad",
    "D03": "D03 Gastos funerales",
    "D04": "D04 Donativos",
    "D05": "D05 Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)",
    "D06": "D06 Aportaciones voluntarias al SAR",
    "D07": "D07 Primas por seguros de gastos médicos",
    "D08": "D08 Gastos de transportación escolar obligatoria",
    "D09": "D09 Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones",
    "D10": "D10 Pagos por servicios educativos (colegiaturas)",
    "S01": "S01 Sin efectos fiscales",
    "CP01": "CP01 Pagos",
    "CN01": "CN01 Nómina",
    "P01": "P01 Por definir"
    }
c_FormaPago = {
    "01": "01 Efectivo",
    "02": "02 Cheque nominativo",
    "03": "03 Transferencia electrónica de fondos",
    "04": "04 Tarjeta de crédito",
    "05": "05 Monedero electrónico",
    "06": "06 Dinero electrónico",
    "08": "08 Vales de despensa",
    "12": "12 Dación en pago",
    "13": "13 Pago por subrogación",
    "14": "14 Pago por consignación",
    "15": "15 Condonación",
    "17": "17 Compensación",
    "23": "23 Novación",
    "24": "24 Confusión",
    "25": "25 Remisión de deuda",
    "26": "26 Prescripción o caducidad",
    "27": "27 A satisfacción del acreedor",
    "28": "28 Tarjeta de débito",
    "29": "29 Tarjeta de servicios",
    "30": "30 Aplicación de anticipos",
    "31": "31 Intermediario pagos",
    "99": "99 Por definir"
    }
c_Exportacion = {
    "01": "01 No aplica",
    "02": "02 Definitiva con clave A1",
    "03": "03 Temporal",
    "04": "04 Definitiva con clave distinta a A1 o cuando no existe enajenación en términos del CFF"
    }
c_RegimenFiscal = {
    "601": "601 General de Ley Personas Morales",
    "603": "603 Personas Morales con Fines no Lucrativos",
    "605": "605 Sueldos y Salarios e Ingresos Asimilados a Salarios",
    "606": "606 Arrendamiento",
    "607": "607 Régimen de Enajenación o Adquisición de Bienes",
    "608": "608 Demás ingresos",
    "609": "609 Consolidación",
    "610": "610 Residentes en el Extranjero sin Establecimiento Permanente en México",
    "611": "611 Ingresos por Dividendos (socios y accionistas)",
    "612": "612 Personas Físicas con Actividades Empresariales y Profesionales",
    "614": "614 Ingresos por intereses",
    "615": "615 Régimen de los ingresos por obtención de premios",
    "616": "616 Sin obligaciones fiscales",
    "620": "620 Sociedades Cooperativas de Producción que optan por diferir sus ingresos",
    "621": "621 Incorporación Fiscal",
    "622": "622 Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras",
    "623": "623 Opcional para Grupos de Sociedades",
    "624": "624 Coordinados",
    "625": "625 Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas",
    "626": "626 Régimen Simplificado de Confianza",
    "628": "628 Hidrocarburos",
    "629": "629 De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales",
    "630": "630 Enajenación de acciones en bolsa de valores"
    }
c_PeriodicidadPago = {
    "01": "01 Diario",
    "02": "02 Semanal",
    "03": "03 Catorcenal",
    "04": "04 Quincenal",
    "05": "05 Mensual",
    "06": "06 Bimestral",
    "07": "07 Unidad obra",
    "08": "08 Comisión",
    "09": "09 Precio alzado",
    "10": "10 Decenal",
    "99": "99 Otra Periodicidad"
    }
c_TipoContrato = {
    "01": "01 Contrato de trabajo por tiempo indeterminado",
    "02": "02 Contrato de trabajo para obra determinada",
    "03": "03 Contrato de trabajo por tiempo determinado",
    "04": "04 Contrato de trabajo por temporada",
    "05": "05 Contrato de trabajo sujeto a prueba",
    "06": "06 Contrato de trabajo con capacitación inicial",
    "07": "07 Modalidad de contratación por pago de hora laborada",
    "08": "08 Modalidad de trabajo por comisión laboral",
    "09": "09 Modalidades de contratación donde no existe relación de trabajo",
    "10": "10 Jubilación, pensión, retiro",
    "99": "99 Otro contrato"
    }
c_TipoJornada = {
    "01": "01 Diurna",
    "02": "02 Nocturna",
    "03": "03 Mixta",
    "04": "04 Por hora",
    "05": "05 Reducida",
    "06": "06 Continuada",
    "07": "07 Partida",
    "08": "08 Por turnos",
    "99": "99 Otra Jornada"
    }
c_TipoRegimen = {
    "02": "02 Sueldos (Incluye ingresos señalados en la fracción I del artículo 94 de LISR)",
    "03": "03 Jubilados",
    "04": "04 Pensionados",
    "05": "05 Asimilados Miembros Sociedades Cooperativas Produccion",
    "06": "06 Asimilados Integrantes Sociedades Asociaciones Civiles",
    "07": "07 Asimilados Miembros consejos",
    "08": "08 Asimilados comisionistas",
    "09": "09 Asimilados Honorarios",
    "10": "10 Asimilados acciones",
    "11": "11 Asimilados otros",
    "12": "12 Jubilados o Pensionados",
    "13": "13 Indemnización o Separación"
    }
c_RiesgoPuesto = {
    "1": "1 Clase I",
    "2": "2 Clase II",
    "3": "3 Clase III",
    "4": "4 Clase IV",
    "5": "5 Clase V",
    "99": "99 No aplica"
    }
c_percepciones = {
    "001": "Sueldos, Salarios  Rayas y Jornales",
    "002": "Gratificación Anual (Aguinaldo)",
    "003": "Participación de los Trabajadores en las Utilidades PTU",
    "004": "Reembolso de Gastos Médicos Dentales y Hospitalarios",
    "005": "Fondo de Ahorro",
    "006": "Caja de ahorro",
    "009": "Contribuciones a Cargo del Trabajador Pagadas por el Patrón",
    "010": "Premios por puntualidad",
    "011": "Prima de Seguro de vida",
    "012": "Seguro de Gastos Médicos Mayores",
    "013": "Cuotas Sindicales Pagadas por el Patrón",
    "014": "Subsidios por incapacidad",
    "015": "Becas para trabajadores y/o hijos",
    "019": "Horas extra",
    "020": "Prima dominical",
    "021": "Prima vacacional",
    "022": "Prima por antigüedad",
    "023": "Pagos por separación",
    "024": "Seguro de retiro",
    "025": "Indemnizaciones",
    "026": "Reembolso por funeral",
    "027": "Cuotas de seguridad social pagadas por el patrón",
    "028": "Comisiones",
    "029": "Vales de despensa",
    "030": "Vales de restaurante",
    "031": "Vales de gasolina",
    "032": "Vales de ropa",
    "033": "Ayuda para renta",
    "034": "Ayuda para artículos escolares",
    "035": "Ayuda para anteojos",
    "036": "Ayuda para transporte",
    "037": "Ayuda para gastos de funeral",
    "038": "Otros ingresos por salarios",
    "039": "Jubilaciones, pensiones o haberes de retiro",
    "044": "Jubilaciones, pensiones o haberes de retiro en parcialidades",
    "045": "Ingresos en acciones o títulos valor que representan bienes",
    "046": "Ingresos asimilados a salarios",
    "047": "Alimentación diferentes a los establecidos en el Art 94 último párrafo LISR",
    "048": "Habitación",
    "049": "Premios por asistencia",
    "050": "Viáticos",
    "051": "Pagos por gratificaciones, primas, compensaciones, recompensas u otros a extrabajadores derivados de jubilación en parcialidades",
    "052": "Pagos que se realicen a extrabajadores que obtengan una jubilación en parcialidades derivados de la ejecución de resoluciones judicial o de un laudo",
    "053": "Pagos que se realicen a extrabajadores que obtengan una jubilación en una sola exhibición derivados de la ejecución de resoluciones judicial o de un laudo",
    }
c_deducciones = {
    "001": "Seguridad social",
    "002": "ISR",
    "003": "Aportaciones a retiro, cesantía en edad avanzada y vejez",
    "004": "Otros",
    "005": "Aportaciones a Fondo de vivienda",
    "006": "Descuento por incapacidad",
    "007": "Pensión alimenticia",
    "008": "Renta",
    "009": "Préstamos provenientes del Fondo Nacional de la Vivienda para los Trabajadores",
    "010": "Pago por crédito de vivienda",
    "011": "Pago de abonos INFONACOT",
    "012": "Anticipo de salarios",
    "013": "Pagos hechos con exceso al trabajador",
    "014": "Errores",
    "015": "Pérdidas",
    "016": "Averías",
    "017": "Adquisición de artículos producidos por la empresa o establecimiento",
    "018": "Cuotas para la constitución y fomento de sociedades cooperativas y de cajas de ahorro",
    "019": "Cuotas sindicales",
    "020": "Ausencia (Ausentismo)",
    "021": "Cuotas obrero patronales",
    "022": "Impuestos Locales",
    "023": "Aportaciones voluntarias",
    "024": "Ajuste en Gratificación Anual (Aguinaldo) Exento",
    "025": "Ajuste en Gratificación Anual (Aguinaldo) Gravado",
    "026": "Ajuste en Participación de los Trabajadores en las Utilidades PTU Exento",
    "027": "Ajuste en Participación de los Trabajadores en las Utilidades PTU Gravado",
    "028": "Ajuste en Reembolso de Gastos Médicos Dentales y Hospitalarios Exento",
    "029": "Ajuste en Fondo de ahorro Exento",
    "030": "Ajuste en Caja de ahorro Exento",
    "031": "Ajuste en Contribuciones a Cargo del Trabajador Pagadas por el Patrón Exento",
    "032": "Ajuste en Premios por puntualidad Gravado",
    "033": "Ajuste en Prima de Seguro de vida Exento",
    "034": "Ajuste en Seguro de Gastos Médicos Mayores Exento",
    "035": "Ajuste en Cuotas Sindicales Pagadas por el Patrón Exento",
    "036": "Ajuste en Subsidios por incapacidad Exento",
    "037": "Ajuste en Becas para trabajadores y/o hijos Exento",
    "038": "Ajuste en Horas extra Exento",
    "039": "Ajuste en Horas extra Gravado",
    "040": "Ajuste en Prima dominical Exento",
    "041": "Ajuste en Prima dominical Gravado",
    "042": "Ajuste en Prima vacacional Exento",
    "043": "Ajuste en Prima vacacional Gravado",
    "044": "Ajuste en Prima por antigüedad Exento",
    "045": "Ajuste en Prima por antigüedad Gravado",
    "046": "Ajuste en Pagos por separación Exento",
    "047": "Ajuste en Pagos por separación Gravado",
    "048": "Ajuste en Seguro de retiro Exento",
    "049": "Ajuste en Indemnizaciones Exento",
    "050": "Ajuste en Indemnizaciones Gravado",
    "051": "Ajuste en Reembolso por funeral Exento",
    "052": "Ajuste en Cuotas de seguridad social pagadas por el patrón Exento",
    "053": "Ajuste en Comisiones Gravado",
    "054": "Ajuste en Vales de despensa Exento",
    "055": "Ajuste en Vales de restaurante Exento",
    "056": "Ajuste en Vales de gasolina Exento",
    "057": "Ajuste en Vales de ropa Exento",
    "058": "Ajuste en Ayuda para renta Exento",
    "059": "Ajuste en Ayuda para artículos escolares Exento",
    "060": "Ajuste en Ayuda para anteojos Exento",
    "061": "Ajuste en Ayuda para transporte Exento",
    "062": "Ajuste en Ayuda para gastos de funeral Exento",
    "063": "Ajuste en Otros ingresos por salarios Exento",
    "064": "Ajuste en Otros ingresos por salarios Gravado",
    "065": "Ajuste en Jubilaciones, pensiones o haberes de retiro en una sola exhibición Exento ",
    "066": "Ajuste en Jubilaciones, pensiones o haberes de retiro en una sola exhibición Gravado",
    "067": "Ajuste en Pagos por separación Acumulable",
    "068": "Ajuste en Pagos por separación No acumulable",
    "069": "Ajuste en Jubilaciones, pensiones o haberes de retiro en parcialidades Exento",
    "070": "Ajuste en Jubilaciones, pensiones o haberes de retiro en parcialidades Gravado",
    "071": "Ajuste en Subsidio para el empleo (efectivamente entregado al trabajador)",
    "072": "Ajuste en Ingresos en acciones o títulos valor que representan bienes Exento",
    "073": "Ajuste en Ingresos en acciones o títulos valor que representan bienes Gravado",
    "074": "Ajuste en Alimentación Exento",
    "075": "Ajuste en Alimentación Gravado",
    "076": "Ajuste en Habitación Exento",
    "077": "Ajuste en Habitación Gravado",
    "078": "Ajuste en Premios por asistencia",
    "079": "Ajuste en Pagos distintos a los listados y que no deben considerarse como ingreso por sueldos, salarios o ingresos asimilados",
    "080": "Ajuste en Viáticos gravados",
    "081": "Ajuste en Viáticos (entregados al trabajador)",
    "082": "Ajuste en Fondo de ahorro Gravado",
    "083": "Ajuste en Caja de ahorro Gravado",
    "084": "Ajuste en Prima de Seguro de vida Gravado",
    "085": "Ajuste en Seguro de Gastos Médicos Mayores Gravado",
    "086": "Ajuste en Subsidios por incapacidad Gravado",
    "087": "Ajuste en Becas para trabajadores y/o hijos Gravado",
    "088": "Ajuste en Seguro de retiro Gravado",
    "089": "Ajuste en Vales de despensa Gravado",
    "090": "Ajuste en Vales de restaurante Gravado",
    "091": "Ajuste en Vales de gasolina Gravado",
    "092": "Ajuste en Vales de ropa Gravado",
    "093": "Ajuste en Ayuda para renta Gravado",
    "094": "Ajuste en Ayuda para artículos escolares Gravado",
    "095": "Ajuste en Ayuda para anteojos Gravado",
    "096": "Ajuste en Ayuda para transporte Gravado",
    "097": "Ajuste en Ayuda para gastos de funeral Gravado",
    "098": "Ajuste a ingresos asimilados a salarios gravados",
    "099": "Ajuste a ingresos por sueldos y salarios gravados",
    "100": "Ajuste en Viáticos exentos",
    "101": "ISR Retenido de ejercicio anterior",
    "102": "Ajuste a pagos por gratificaciones, primas, compensaciones, recompensas u otros a extrabajadores derivados de jubilación en parcialidades, gravados",
    "103": "Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en parcialidades derivados de la ejecución de una resolución judicial o de un laudo gravados",
    "104": "Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en parcialidades derivados de la ejecución de una resolución judicial o de un laudo exentos",
    "105": "Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en una sola exhibición derivados de la ejecución de una resolución judicial o de un laudo gravados",
    "106": "Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en una sola exhibición derivados de la ejecución de una resolución judicial o de un laudo exentos",
    "107": "Ajuste al Subsidio Causado",
    }
c_otrospagos = {
    "001": "Reintegro de ISR pagado en exceso (siempre que no haya sido enterado al SAT)",
    "002": "Subsidio para el empleo (efectivamente entregado al trabajador)",
    "003": "Viáticos (entregados al trabajador)",
    "004": "Aplicación de saldo a favor por compensación anual",
    "005": "Reintegro de ISR retenido en exceso de ejercicio anterior (siempre que no haya sido enterado al SAT)",
    "006": "Alimentos en bienes (Servicios de comedor y comida) Art 94 último párrafo LISR",
    "007": "ISR ajustado por subsidio",
    "008": "Subsidio efectivamente entregado que no correspondía (Aplica sólo cuando haya ajuste al cierre de mes en relación con el Apéndice 7 de la guía de llenado de nómina)",
    "009": "Reembolso de descuentos efectuados para el crédito de vivienda",
    "999": "Pagos distintos a los listados y que no deben considerarse como ingreso por sueldos, salarios o ingresos asimilados"
    }
c_retencion = {
    "01": "01 Servicios profesionales",
    "02": "02 Regalías por derechos de autor",
    "03": "03 Autotransporte terrestre de carga",
    "04": "04 Servicios prestados por comisionistas",
    "05": "05 Arrendamiento",
    "06": "06 Enajenación de acciones",
    "07": "07 Enajenación de bienes objeto de la LIEPS, a través de mediadores, agentes, representantes, corredores, consignatarios o distribuidores",
    "08": "08 Enajenación de bienes inmuebles consignada en escritura pública",
    "09": "09 Enajenación de otros bienes, no consignada en escritura pública",
    "10": "10 Adquisición de desperdicios industriales",
    "11": "11 Adquisición de bienes consignada en escritura pública",
    "12": "12 Adquisición de otros bienes, no consignada en escritura pública",
    "13": "13 Otros retiros de AFORE",
    "14": "14 Dividendos o utilidades distribuidas",
    "15": "15 Remanente distribuible",
    "16": "16 Intereses",
    "17": "18 Arrendamiento en fideicomiso",
    "18": "18 Pagos realizados a favor de residentes en el extranjero",
    "19": "19 Enajenación de acciones u operaciones en bolsa de valores",
    "20": "20 Obtención de premios",
    "21": "21 Fideicomisos que no realizan actividades empresariales",
    "22": "22 Planes personales de retiro",
    "23": "23 Intereses reales deducibles por créditos hipotecarios",
    "24": "24 Operaciones Financieras Derivadas de Capital",
    "25": "25 Otro tipo de retenciones",
    "26": "26 Servicios mediante Plataformas Tecnológicas",
    "27": "27 Sector Financiero",
    "28": "28 Pagos y retenciones a Contribuyentes del RIF"
    }
c_pago = {
    "01": "01 Pago definitivo IVA",
    "02": "02 Pago definitivo IEPS",
    "03": "03 Pago definitivo ISR ",
    "04": "04 Pago provisional ISR"
    }
c_glosa = {
    "501.asc": "501 Datos Generales",
    "502.asc": "502 Transporte",
    "503.asc": "503 Guías",
    "504.asc": "504 Contenedores",
    "505.asc": "505 Facturas",
    "506.asc": "506 Fechas pedimento",
    "507.asc": "507 Casos pedimento",
    "508.asc": "508 Cuentas garantía pedimento",
    "509.asc": "509 Tasas pedimento",
    "510.asc": "510 Contribuciones pedimento",
    "511.asc": "511 Observaciones pedimento",
    "512.asc": "512 Descargos",
    "520.asc": "520 Destinatarios",
    "701.asc": "701 Rectificaciones",
    "702.asc": "702 Diferencias de contribuciones",
    "Sel.asc": "Selección automatizada",
    "551.asc": "551 Partidas",
    "552.asc": "552 Mercancías",
    "553.asc": "553 Permisos (RRNA)",
    "554.asc": "554 Casos partida",
    "555.asc": "555 Cuentas garantía partida",
    "556.asc": "556 Tasas contribuciones partida",
    "557.asc": "557 Contribuciones partida",
    "558.asc": "558 Observaciones partida",
    "nci.asc": "Incidencias",
    "men.asc": "Resumen"
    }
c_impuesto = {
    1: "ISR",
    2: "IVA",
    3: "IEPS",
    }
c_efos = {
    "100": "Se encontro en el listado de EFOS"
}

def c_invoice(version):

    values = {
        "3.2": {
            "rfc": "rfc",
            "total": "total",
            "tipo": "tipoDeComprobante",
            "fecha": "fecha",
            "serie": "serie",
            "folio": "folio",
            "nombre": "nombre",
            "metodo": "metodoDePago",
            "forma": "formaDePago",
            "descripcion": "descripcion",
            "noidentificacion": "noIdentificacion",
            "cantidad": "cantidad",
            "valor": "valorUnitario",
            "importe": "importe",
            "subtotal": "subTotal",
            "impuesto": "impuesto",
            "isr": "ISR",
            "iva": "IVA",
            "ieps": "IEPS",
            "descuento": "descuento"
        },
        "global": {
            "rfc": "Rfc",
            "total": "Total",
            "tipo": "TipoDeComprobante",
            "fecha": "Fecha",
            "serie": "Serie",
            "folio": "Folio",
            "nombre": "Nombre",
            "metodo": "MetodoPago",
            "forma": "FormaPago",
            "descripcion": "Descripcion",
            "noidentificacion": "NoIdentificacion",
            "cantidad": "Cantidad",
            "valor": "ValorUnitario",
            "importe": "Importe",
            "subtotal": "SubTotal",
            "impuesto": "Impuesto",
            "isr": "001",
            "iva": "002",
            "ieps": "003",
            "descuento": "Descuento"
        }
    }
    
    return values.get(version, values.get("global"))

def c_retenciones(version):

    values = {
        "1.0": {
            "rfc_emisor": "RFCEmisor",
            "nacionalidad": "Nacionalidad",
            "rfc_receptor": "RFCRecep",
            "curp": "CURPR",
            "tax_id": "NumRegIdTrib",
            "ejercicio": "Ejerc",
            "total": "montoTotOperacion",
            "total_gravado": "montoTotGrav",
            "total_exento": "montoTotExent",
            "total_retenido": "montoTotRet",
            "impuesto_retenido": "Impuesto",
            "isr": "01",
            "iva": "02",
            "ieps": "03",
            "monto_retenido": "montoRet"
        },
        "global": {
            "rfc_emisor": "RfcE",
            "nacionalidad": "NacionalidadR",
            "rfc_receptor": "RfcR",
            "curp": "CurpR",
            "tax_id": "NumRegIdTribR",
            "ejercicio": "Ejercicio",
            "total": "MontoTotOperacion",
            "total_gravado": "MontoTotGrav",
            "total_exento": "MontoTotExent",
            "total_retenido": "MontoTotRet",
            "impuesto_retenido": "ImpuestoRet",
            "isr": "001",
            "iva": "002",
            "ieps": "003",
            "monto_retenido": "MontoRet"
        }
    }

    return values.get(version, values.get("global"))

list_impuesto = [
    ('iva', 'Traslados', 'Traslado', 'Base'),
    ('iva', 'Traslados', 'Traslado', 'Importe'),
    ('iva', 'Traslados', 'Traslado', 'TasaOCuota'),
    ('iva', 'Traslados', 'Traslado', 'TipoFactor'),
    ('iva', 'Retenciones', 'Retencion', 'Base'),
    ('iva', 'Retenciones', 'Retencion', 'Importe'),
    ('iva', 'Retenciones', 'Retencion', 'TasaOCuota'),
    ('iva', 'Retenciones', 'Retencion', 'TipoFactor'),
    ('ieps', 'Traslados', 'Traslado', 'Base'),
    ('ieps', 'Traslados', 'Traslado', 'Importe'),
    ('ieps', 'Traslados', 'Traslado', 'TasaOCuota'),
    ('ieps', 'Traslados', 'Traslado', 'TipoFactor'),
    ('ieps', 'Retenciones', 'Retencion', 'Base'),
    ('ieps', 'Retenciones', 'Retencion', 'Importe'),
    ('ieps', 'Retenciones', 'Retencion', 'TasaOCuota'),
    ('ieps', 'Retenciones', 'Retencion', 'TipoFactor'),
    ('isr', 'Retenciones', 'Retencion', 'Base'),
    ('isr', 'Retenciones', 'Retencion', 'Importe'),
    ('isr', 'Retenciones', 'Retencion', 'TasaOCuota'),
    ('isr', 'Retenciones', 'Retencion', 'TipoFactor')
    ]

nomina_types = [
    ("Percepciones", "Percepcion", "TipoPercepcion"),
    ("Deducciones", "Deduccion", "TipoDeduccion"),
    ("OtrosPagos", "OtroPago", "TipoOtroPago")]

c_nomina = {
    "TipoPercepcion": c_percepciones,
    "TipoDeduccion": c_deducciones,
    "TipoOtroPago": c_otrospagos
}

global_numeric = [
    "Tipo de cambio",
    "Subtotal",
    "IVA trasladado",
    "IEPS trasladado",
    "Impuesto local trasladado",
    "ISR retenido",
    "IVA retenido",
    "IEPS retenido",
    "Impuesto local retenido",
    "Descuento",
    "Total"
    ]

global_negative = [
    "ISR retenido",
    "IVA retenido",
    "IEPS retenido",
    "Impuesto local retenido",
    "Descuento",
]

concept_explode = [
    "Clave de prodserv",
    "Descripción",
    "Número identificación",
    "Clave de unidad",
    "Cantidad",
    "Valor unitario",
    "Importe",
    "Descuento",
    "IVA base traslado",
    "IVA importe traslado",
    "IVA tasaocuota traslado",
    "IVA tipofactor traslado",
    "IEPS base traslado",
    "IEPS importe traslado",
    "IEPS tasaocuota traslado",
    "IEPS tipofactor traslado",
    "ISR base retencion",
    "ISR importe retencion",
    "ISR tasaocuota retencion",
    "ISR tipofactor retencion",
    "IVA base retencion",
    "IVA importe retencion",
    "IVA tasaocuota retencion",
    "IVA tipofactor retencion",
    "IEPS base retencion",
    "IEPS importe retencion",
    "IEPS tasaocuota retencion",
    "IEPS tipofactor retencion"
]

concept_numeric = [
    "Valor unitario",
    "Importe",
    "Descuento",
    "IVA base traslado",
    "IVA importe traslado",
    "IEPS base traslado",
    "IEPS importe traslado",
    "ISR base retencion",
    "ISR importe retencion",
    "IVA base retencion",
    "IVA importe retencion",
    "IEPS base retencion",
    "IEPS importe retencion"
]

concept_negative = [
    "Descuento",
    "ISR base retencion",
    "ISR importe retencion",
    "IVA base retencion",
    "IVA importe retencion",
    "IEPS base retencion",
    "IEPS importe retencion"
]

payment_explode = [
    "Método de pago",
    "Serie de documento",
    "Folio de documento",
    "UUID de documento",
    "Número de parcialidad",
    "Moneda de documento",
    "Equivalencia de documento",
    "Saldo anterior",
    "Importe pagado",
    "Saldo insoluto",
    "IVA traslado",
    "IEPS traslado",
    "ISR retencion",
    "IVA retencion",
    "IEPS retencion"
]

payment_numeric = [
    "Total base IVA exento",
    "Total base IVA 0% traslado",
    "Total IVA 0% traslado",
    "Total base IVA 8% traslado",
    "Total IVA 8% traslado",
    "Total base IVA 16% traslado",
    "Total IVA 16% traslado",
    "Total retenciones ISR",
    "Total retenciones IVA",
    "Total retenciones IEPS",
    "Monto",
    "Total pagos",
    "Saldo insoluto",
    "Importe pagado",
    "Saldo anterior",
    "Equivalencia de documento"
]

payment_date = [
    "Fecha",
    "Fecha de pago"
]

payroll_explode = [
    "Versión",
    "CURP",
    "Número de seguridad social",
    "Fecha de inicio de relación laboral",
    "Antigüedad",
    "Tipo de contrato",
    "Sindicalizado",
    "Tipo de jornada",
    "Tipo de régimen",
    "Número de empleado",
    "Riesgo de puesto",
    "Periodicidad de pago",
    "Salario base de cot apor",
    "Salario diario integrado",
    "Clave entidad federativa",
    "Departamento",
    "Puesto",
    "Registro patronal",
    "Subcontratación RFC",
    "Subcontratación porcentaje",
    "Tipo de nómina",
    "Número de días pagados",
    "Fecha de pago",
    "Fecha inicial de pago",
    "Fecha final de pago",
    "Total de percepciones",
    "Total de deducciones",
    "Total de otros pagos",
]

payroll_numeric = [
    "Salario base de cot apor",
    "Salario diario integrado",
    "Número de días pagados",
    "Total de percepciones",
    "Total de deducciones",
    "Total de otros pagos",
    "Total"
]

payroll_date = [
    "Fecha",
    "Fecha de inicio de relación laboral",
    "Fecha inicial de pago",
    "Fecha final de pago",
    "Fecha de pago"
]